"""Build the one-click demo sample library for the web app.

Copies a small set of held-out clips into web/public/samples/, runs each through the live ProofVoice API
to capture a reference report, and writes web/public/samples/manifest.json.

Every clip is from the group-disjoint validation split (never trained on) or from Grok Voice (a generator
never seen in training). Reports are real API output, stored so the hosted UI can show them when no
backend is reachable, and always labeled as precomputed there.

Run from the repo root with the API up:  .venv/Scripts/python web/scripts/build-samples.py
"""
from __future__ import annotations

import datetime as dt
import json
import shutil
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "web" / "public" / "samples"
API = "http://127.0.0.1:8000"
DIFF = "data/hearsay/train/DiffSSD/generated_speech"
LIBRI = "data/external/LibriSpeech"

LIBRI_CREDIT = "LibriSpeech (Panayotov et al., 2015), CC BY 4.0"
LJ_CREDIT = "LJ Speech (Ito & Johnson, 2017), public domain"
DIFF_CREDIT = "DiffSSD (Bhagtani et al., 2024), provided via NSA HEARSAY"
GROK_CREDIT = "Generated by the ProofVoice team with xAI Grok Voice"

SAMPLES = [
    # id, title, truth, group, source path, credit, note
    ("real-libri-908", "Audiobook, male voice", "bonafide", "Real speech",
     f"{LIBRI}/test-clean/908/157963/908-157963-0030.flac", LIBRI_CREDIT, "LibriSpeech speaker 908"),
    ("real-libri-1284", "Audiobook, female voice", "bonafide", "Real speech",
     f"{LIBRI}/test-clean/1284/1180/1284-1180-0007.flac", LIBRI_CREDIT, "LibriSpeech speaker 1284"),
    ("real-libri-174", "Audiobook, second male voice", "bonafide", "Real speech",
     f"{LIBRI}/dev-clean/174/50561/174-50561-0000.flac", LIBRI_CREDIT, "LibriSpeech speaker 174"),
    ("real-lj", "Public-domain reading", "bonafide", "Real speech",
     "data/hearsay/train/ljreal/LJ015-0075.wav", LJ_CREDIT, "LJ Speech, single speaker"),
    ("fake-elevenlabs", "ElevenLabs voice clone", "spoof", "Commercial voice clones",
     f"{DIFF}/elevenlabs/speaker_6167/sentence_329.mp3", DIFF_CREDIT, "Cloned from a real speaker, MP3"),
    ("fake-playht", "PlayHT voice clone", "spoof", "Commercial voice clones",
     f"{DIFF}/playht/speaker_2061/sentence_135.wav", DIFF_CREDIT, "Cloned from a real speaker"),
    ("fake-xtts", "XTTS v2 zero-shot clone", "spoof", "Open-source TTS",
     f"{DIFF}/xtts_v2/speaker_6167/sentence_218.wav", DIFF_CREDIT, "Open-source zero-shot cloning"),
    ("fake-openvoice", "OpenVoice v2 clone", "spoof", "Open-source TTS",
     f"{DIFF}/openvoicev2/speaker_2061/sentence_441_en-us.wav", DIFF_CREDIT, "Open-source voice conversion"),
    ("grok-urgent", "Grok Voice: grandparent scam", "spoof", "Unseen generator (Grok Voice)",
     "data/grok_samples/sample_01_urgent_relative.wav", GROK_CREDIT, "Generator never seen in training"),
    ("grok-ceo", "Grok Voice: CEO wire fraud", "spoof", "Unseen generator (Grok Voice)",
     "data/grok_samples/sample_02_ceo_wire.wav", GROK_CREDIT, "Generator never seen in training"),
    ("hard-elevenlabs-2061", "Known hard case: ElevenLabs", "spoof", "Known hard case",
     f"{DIFF}/elevenlabs/speaker_2061/sentence_134.mp3", DIFF_CREDIT,
     "The weakest measured subgroup (speaker 2061, subgroup minDCF 0.24). Shown on purpose: the detector misses this one."),
]


def libri_transcript(path: Path) -> str | None:
    utt = path.stem
    trans = path.parent / f"{'-'.join(utt.split('-')[:2])}.trans.txt"
    if not trans.exists():
        return None
    for line in trans.read_text().splitlines():
        if line.startswith(utt + " "):
            return line.split(" ", 1)[1].capitalize()
    return None


def transcript(src: Path) -> str | None:
    if src.suffix == ".flac":
        return libri_transcript(src)
    meta = src.with_suffix(".json")
    if meta.exists():
        return json.loads(meta.read_text()).get("text")
    return None


def main() -> None:
    health = requests.get(f"{API}/health", timeout=10).json()
    (OUT / "reports").mkdir(parents=True, exist_ok=True)
    items = []
    for sid, title, truth, group, rel, credit, note in SAMPLES:
        src = ROOT / rel
        dest = OUT / f"{sid}{src.suffix}"
        shutil.copyfile(src, dest)
        r = requests.post(f"{API}/analyze/file", files={"file": (dest.name, dest.read_bytes())}, timeout=300)
        r.raise_for_status()
        report = r.json()
        (OUT / "reports" / f"{sid}.json").write_text(json.dumps(report, indent=1))
        items.append({
            "id": sid,
            "title": title,
            "group": group,
            "truth": truth,
            "file": f"/samples/{dest.name}",
            "report": f"/samples/reports/{sid}.json",
            "duration_s": report["file"].get("duration_s"),
            "bytes": dest.stat().st_size,
            "transcript": transcript(src),
            "note": note,
            "credit": credit,
            "held_out": True,
        })
        print(f"{sid:24s} truth={truth:8s} p={report['synthetic_probability']:.3f} {report['status']}")
    manifest = {
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "detector": health.get("detector", {}),
        "samples": items,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=1))
    print(f"wrote {len(items)} samples to {OUT}")


if __name__ == "__main__":
    main()
